const products = [
  {
    id: 1,

    category: "home",
    sub_category: "pillows",
    price: 1599,
    img: "./images/almofada1.jpg",
    title: `single leaf pillow `,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 1099,
    amount: 1,
    featured: true,
  },
  {
    id: 2,

    category: "home",
    sub_category: "pillows",
    price: 1799,
    img: "./images/almofada2.jpg",
    title: `autumn leaves pillow `,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 0,
    amount: 1,
  },
  {
    id: 3,

    category: "home",
    sub_category: "pillows",
    price: 1699,
    img: "./images/almofada3.jpg",
    title: `mirror-effect leaves pillow `,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 0,
    sale: 1499,
    amount: 1,
  },
  {
    id: 4,

    category: "accessories",
    sub_category: "earrings",
    price: 599,
    img: "./images/earrings.jpg",
    title: `black sand bottle earrings `,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 6,
    sale: 0,
    amount: 1,
    featured: true,
  },
  {
    id: 5,

    category: "accessories",
    sub_category: "necklace",
    price: 599,
    img: "./images/pendant1.jpg",
    title: `flower necklace  `,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 0,
    sale: 0,
    amount: 1,
  },
  {
    id: 6,

    category: "health & personal care",
    sub_category: "face mask",
    price: 800,
    img: "./images/mascaras_tecidos.jpg",
    title: `cotton mask `,
    detail:
      "This cotton face mask has a pocket for a filter,  3 filters are included.",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 700,
    amount: 1,
    featured: true,
  },
  {
    id: 7,

    category: "health & personal care",
    sub_category: "feminine hygiene",
    price: 3500,
    img: "./images/pensos_flores.jpg",
    title: `pack of 5 sanitary pads`,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 0,
    amount: 1,
    featured: true,
  },
  {
    id: 8,

    category: "health & personal care",
    sub_category: "feminine hygiene",
    price: 600,
    img: "./images/pensos_mundo.jpg",
    title: `single sanitary pad`,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 8,
    sale: 0,
    amount: 1,
  },
  {
    id: 9,

    category: "bags",
    sub_category: "produce bags",
    price: 1600,
    img: "./images/produceBags.png",
    title: `pack of 3  produce bags `,
    detail: "made from fishing nets",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 0,
    amount: 1,
    featured: true,
  },
  {
    id: 10,

    category: "bags",
    sub_category: "tote bags",
    price: 1300,
    img: "./images/toteBag1.jpg",
    title: `Nature lover tote bag`,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 1200,
    amount: 1,
    featured: true,
  },
  {
    id: 11,

    category: "bags",
    sub_category: "tote bags",
    price: 1300,
    img: "./images/toteBag2.jpg",
    title: `pocket leaves tote bag`,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 1200,
    amount: 1,
  },
  {
    id: 12,

    category: "bags",
    sub_category: "tote bags",
    price: 1800,
    img: "./images/reversibleBag.jpg",
    title: `reversible tote bag`,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 1699,
    amount: 1,
  },
];

export default products;
