const products = [
  {
    id: 1,
    title: "pillow a",
    category: "pillows",
    price: 1599,
    img: "./images/almofada1.jpg",
    desc: `single leaf pillow `,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 1099,
    amount: 1,
  },
  {
    id: 2,
    title: "pillow c",
    category: "pillows",
    price: 1799,
    img: "./images/almofada2.jpg",
    desc: `autumn leaves pillow `,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 0,
    amount: 1,
  },
  {
    id: 3,
    title: "pillow b",
    category: "pillows",
    price: 1699,
    img: "./images/almofada3.jpg",
    desc: `mirror-effect leaves pillow `,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 0,
    sale: 1499,
    amount: 1,
  },
  {
    id: 4,
    title: "earrings",
    category: "accessories",
    price: 599,
    img: "./images/earrings.jpg",
    desc: `black sand bottle earrings `,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 6,
    sale: 0,
    amount: 1,
  },
  {
    id: 5,
    title: "pendant",
    category: "accessories",
    price: 599,
    img: "./images/pendant1.jpg",
    desc: `flower preserved in resin  `,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 0,
    sale: 0,
    amount: 1,
  },
  {
    id: 6,
    title: "face mask",
    category: "masks",
    price: 800,
    img: "./images/mascaras_tecidos.jpg",
    desc: `cotton mask with pocket for filter`,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 700,
    amount: 1,
  },
  {
    id: 7,
    title: "sanitary pads",
    category: "sanitary",
    price: 3500,
    img: "./images/pensos_flores.jpg",
    desc: `pack of 5 sanitary pads`,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 0,
    amount: 1,
  },
  {
    id: 8,
    title: "sanitary pads",
    category: "sanitary",
    price: 600,
    img: "./images/pensos_mundo.jpg",
    desc: `single sanitary pad`,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 8,
    sale: 0,
    amount: 1,
  },
  {
    id: 9,
    title: "produce bags",
    category: "produce",
    price: 1600,
    img: "./images/produceBags.png",
    desc: `pack of 3 fishing net produce bags `,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 0,
    amount: 1,
  },
  {
    id: 10,
    title: "tote bag",
    category: "bags",
    price: 1300,
    img: "./images/toteBag1.jpg",
    desc: `Nature lover tote bag`,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 1200,
    amount: 1,
  },
  {
    id: 11,
    title: "tote bag",
    category: "bags",
    price: 1300,
    img: "./images/toteBag2.jpg",
    desc: `leaves in the pocket tote bag`,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 1200,
    amount: 1,
  },
  {
    id: 12,
    title: "tote bag",
    category: "bags",
    price: 1800,
    img: "./images/reversibleBag.jpg",
    desc: `reversible tote bag`,
    detail:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perferendis, iure aliquam. Pariatur ipsa cumque qui sit sequi praesentium architecto nemo inventore fuga ut, quam nobis earum iste quaerat velit ad?",
    thumbnail1: "./images/thumb/thumbnail1.png",
    thumbnail2: "./images/thumb/thumbnail2.png",
    stock: 2,
    sale: 1699,
    amount: 1,
  },
];

export default products;
