const products = [
  {
    id: 1,
    title: "pillow a",
    category: "pillows",
    price: 15.99,
    img: "./images/almofada1.jpg",
    desc: `handmade throw pillow `,
  },
  {
    id: 2,
    title: "pillow c",
    category: "pillows",
    price: 14.99,
    img: "./images/almofada2.jpg",
    desc: `handmade throw pillow `,
  },
  {
    id: 3,
    title: "pillow b",
    category: "pillows",
    price: 16.99,
    img: "./images/almofada3.jpg",
    desc: `handmade throw pillow `,
  },
  {
    id: 4,
    title: "earrings",
    category: "accessories",
    price: 5.99,
    img: "./images/earrings.jpg",
    desc: `wolf bitters  `,
  },
  {
    id: 5,
    title: "pendant",
    category: "accessories",
    price: 5.99,
    img: "./images/pendant1.jpg",
    desc: `I'm baby woke mlkshk  `,
  },
  {
    id: 6,
    title: "face mask",
    category: "masks",
    price: 8,
    img: "./images/mascaras_tecidos.jpg",
    desc: `hammock freegan`,
  },
  {
    id: 7,
    title: "sanitary pads",
    category: "sanitary",
    price: 12.99,
    img: "./images/pensos_flores.jpg",
    desc: `I'm baby woke mlkshk`,
  },
  {
    id: 8,
    title: "sanitary pads",
    category: "sanitary",
    price: 15.99,
    img: "./images/pensos_mundo.jpg",
    desc: `wolf bitters`,
  },
  {
    id: 9,
    title: "produce bags",
    category: "produce",
    price: 6,
    img: "./images/sacoPesca.jpg",
    desc: `Made from recycled`,
  },
  {
    id: 10,
    title: "tote bags",
    category: "bags",
    price: 5.99,
    img: "./images/toteBag1.jpg",
    desc: `Cotton bag`,
  },
  {
    id: 11,
    title: "tote bags",
    category: "bags",
    price: 15.99,
    img: "./images/toteBag2.jpg",
    desc: `Cotton bag`,
  },
  {
    id: 12,
    title: "reversible",
    category: "bags",
    price: 18,
    img: "./images/reversibleBag.png",
    desc: `Cotton bag`,
  },
];

export default products;
